<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>  <!-- format version, almost always 4.0.0 -->

  <artifactId>eureka-server</artifactId> <!-- service name -->
  <name>eureka-server</name> <!-- human readable name -->

  <properties> <!-- versions -->
  </properties>

  <parent>
    <groupId>com.streamsense</groupId>
    <artifactId>streamsense-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>

  <dependencies> <!-- libraries that will be used -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-netflix-eureka-server</artifactId> <!-- eureka core -->
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId> <!-- actuator w health checks, metrics, operational endpoints -->
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId> <!-- test starter -->
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId> <!-- creates executable -->
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
