version: "3.9"

services:
  eureka-server:
    build: ./eureka-server
    ports:
    - "8761:8761" #default port for eureka server

    #debugging since api-gateway is not showing up on eureka, may be because of diff startup timing
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8761/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 20

  config-server:
    build: ./config-server
    ports:
      - "8888:8888" # port for config server
    volumes:
      - ./config-server/config-repo:/config-repo
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:/config-repo
    depends_on:
      - eureka-server

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080" # port for api-gateway
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_started
  
  chat-service:
    build: ./chat-service
    ports: 
    - "8081:8081" # port for chat-service following pattern
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_started
  
  recommendation-service:
    build: ./recommendation-service
    ports:
    - "8082:8082" # following port pattern
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_started
  
  sentiment-service:
    build: ./sentiment-service
    ports:
    - "8083:8083"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_started

  video-service:
    build: ./video-service
    ports:
    - "8084:8084"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_started
  
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000" # so it doesn't collide with frontend at 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    depends_on:
      - prometheus

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"