apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: streamsense
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - prometheus:9090

      - job_name: streamsense-services
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - api-gateway:8080
              - chat-service:8081
              - recommendation-service:8082
              - sentiment-service:8083
              - video-service:8084
              - config-server:8888
              - eureka-server:8761
