#bootstrap to pull config files from config server
spring:
  application:
    name: recommendation-service
  config:
    import: optional:configserver:http://config-server:8888 #config server hosted on docker at port 8888