# config-server/config-repo/api-gateway.yml

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka # url through docker

streamsense:
  topics:
    chatMessages: stream.chat.messages
    sentimentEvents: stream.sentiment.events
  services:
    sentiment-service:
      base-url: http://sentiment-service:8083

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: api-gateway-subscriptions
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.streamsense.apigateway.events
        spring.json.value.default.type: com.streamsense.apigateway.events.ChatMessageEvent
        spring.json.use.type.headers: false
        
  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /graphql

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans