-- The sponsor's logo on a deal, as the streamer uploaded it: what on-screen detection looks for from
-- the moment it is added. At most two per deal (a light and a dark variant, say); the service
-- enforces the count. The bytes live in object storage under object_key; this row is what the deal
-- lists, what the console shows, and what a detection will name by id.
create table deal_logos (
    id bigint generated by default as identity primary key,
    deal_id bigint not null references deals (id) on delete cascade,
    object_key varchar(255) not null,
    content_type varchar(64) not null,
    sha256 varchar(64) not null,
    width integer not null,
    height integer not null,
    size_bytes bigint not null,
    uploaded_at bigint not null
);

create index idx_deal_logos_deal on deal_logos (deal_id, uploaded_at);
