create table analytics_processed_events (
    source_topic varchar(255) not null,
    source_event_id varchar(255) not null,
    streamer varchar(255) not null,
    stream_session_id varchar(255),
    event_timestamp bigint not null,
    processed_at bigint not null,
    primary key (source_topic, source_event_id)
);

create index idx_analytics_processed_streamer_processed_at
    on analytics_processed_events (streamer, processed_at desc);

create index idx_analytics_processed_session_processed_at
    on analytics_processed_events (stream_session_id, processed_at desc);

create table stream_metric_buckets (
    id bigint generated by default as identity primary key,
    streamer varchar(255) not null,
    channel_login varchar(255),
    stream_session_id varchar(255),
    session_key varchar(255) not null,
    twitch_stream_id varchar(255),
    bucket_start bigint not null,
    bucket_size_seconds integer not null,
    chat_message_count bigint not null default 0,
    chat_sentiment_count bigint not null default 0,
    chat_positive_count bigint not null default 0,
    chat_neutral_count bigint not null default 0,
    chat_negative_count bigint not null default 0,
    chat_score_sum double precision not null default 0,
    transcript_sentiment_count bigint not null default 0,
    transcript_positive_count bigint not null default 0,
    transcript_neutral_count bigint not null default 0,
    transcript_negative_count bigint not null default 0,
    transcript_score_sum double precision not null default 0,
    negative_spike_count bigint not null default 0,
    engagement_spike_count bigint not null default 0,
    created_at bigint not null,
    updated_at bigint not null,
    unique (streamer, session_key, bucket_start, bucket_size_seconds)
);

create index idx_stream_metric_bucket_streamer_time
    on stream_metric_buckets (streamer, bucket_start desc);

create index idx_stream_metric_bucket_session_time
    on stream_metric_buckets (session_key, bucket_start desc);

create table stream_bucket_chatters (
    streamer varchar(255) not null,
    session_key varchar(255) not null,
    bucket_start bigint not null,
    bucket_size_seconds integer not null,
    username varchar(255) not null,
    first_seen_at bigint not null,
    primary key (streamer, session_key, bucket_start, bucket_size_seconds, username)
);

create table sponsor_metric_buckets (
    id bigint generated by default as identity primary key,
    streamer varchar(255) not null,
    channel_login varchar(255),
    stream_session_id varchar(255),
    session_key varchar(255) not null,
    twitch_stream_id varchar(255),
    bucket_start bigint not null,
    bucket_size_seconds integer not null,
    sponsor varchar(255) not null,
    detection_count bigint not null default 0,
    accepted_detection_count bigint not null default 0,
    low_confidence_detection_count bigint not null default 0,
    fallback_detection_count bigint not null default 0,
    estimated_exposure_ms bigint not null default 0,
    confidence_sum double precision not null default 0,
    max_confidence double precision,
    created_at bigint not null,
    updated_at bigint not null,
    unique (streamer, session_key, bucket_start, bucket_size_seconds, sponsor)
);

create index idx_sponsor_metric_bucket_streamer_time
    on sponsor_metric_buckets (streamer, bucket_start desc);

create index idx_sponsor_metric_bucket_session_time
    on sponsor_metric_buckets (session_key, bucket_start desc);
