-- One row per stream: a Twitch broadcast seen by the Helix poller (source HELIX) or, when the
-- poller is off or the channel is a replay alias, a capture run derived from the events'
-- streamSessionId (source CAPTURE). Events join to sessions by streamer and time range.
create table stream_sessions (
    id bigint generated by default as identity primary key,
    streamer varchar(255) not null,
    source varchar(16) not null,
    session_ref varchar(255) not null,
    twitch_stream_id varchar(255),
    stream_session_id varchar(255),
    channel_login varchar(255),
    title varchar(512),
    category varchar(255),
    started_at bigint not null,
    ended_at bigint,
    last_seen_at bigint not null,
    peak_viewers integer,
    viewer_sum bigint not null default 0,
    viewer_samples integer not null default 0,
    created_at bigint not null,
    updated_at bigint not null,
    unique (streamer, source, session_ref)
);

create index idx_stream_sessions_streamer_started
    on stream_sessions (streamer, started_at desc);

create index idx_stream_sessions_open
    on stream_sessions (source, ended_at);

-- Viewer counts per poll, so a later query can weight logo exposure by who was watching.
create table stream_session_viewers (
    session_id bigint not null references stream_sessions (id) on delete cascade,
    sampled_at bigint not null,
    viewer_count integer not null,
    primary key (session_id, sampled_at)
);
