-- Per-session analytics for the report: how prominent the logo was, how the sponsor was talked
-- about, and what viewers did in chat. All keyed like the existing buckets (streamer, session_key,
-- bucket) so a session's numbers are the buckets between its start and end.

-- Sum of the detection box areas (width * height, 0..1) of accepted detections, for prominence weighting.
alter table sponsor_metric_buckets add column area_sum double precision not null default 0;

-- Sponsor-relevant sentiment per sponsor and channel (CHAT or VOICE).
create table sponsor_mention_buckets (
    id bigint generated by default as identity primary key,
    streamer varchar(255) not null,
    session_key varchar(255) not null,
    bucket_start bigint not null,
    bucket_size_seconds integer not null,
    sponsor varchar(255) not null,
    channel varchar(16) not null,
    mention_count bigint not null default 0,
    positive_count bigint not null default 0,
    neutral_count bigint not null default 0,
    negative_count bigint not null default 0,
    score_sum double precision not null default 0,
    created_at bigint not null,
    updated_at bigint not null,
    unique (streamer, session_key, bucket_start, bucket_size_seconds, sponsor, channel)
);

create index idx_sponsor_mention_streamer_time
    on sponsor_mention_buckets (streamer, bucket_start desc);

-- Chat commands ("!redbull") and posted link hosts, so a deal's command and tracked link can be counted later.
create table chat_command_buckets (
    streamer varchar(255) not null,
    session_key varchar(255) not null,
    bucket_start bigint not null,
    bucket_size_seconds integer not null,
    command varchar(64) not null,
    use_count bigint not null default 0,
    created_at bigint not null,
    updated_at bigint not null,
    primary key (streamer, session_key, bucket_start, bucket_size_seconds, command)
);

create table chat_command_users (
    streamer varchar(255) not null,
    session_key varchar(255) not null,
    command varchar(64) not null,
    username varchar(255) not null,
    first_seen_at bigint not null,
    primary key (streamer, session_key, command, username)
);

create table chat_link_buckets (
    streamer varchar(255) not null,
    session_key varchar(255) not null,
    bucket_start bigint not null,
    bucket_size_seconds integer not null,
    host varchar(255) not null,
    post_count bigint not null default 0,
    created_at bigint not null,
    updated_at bigint not null,
    primary key (streamer, session_key, bucket_start, bucket_size_seconds, host)
);
