-- One sponsorship deal: a sponsor on a channel over a date range, with the commercial terms the
-- session report prices exposure at and the direct-response signals chat is counted for.
-- Sessions belong to a deal by streamer and start time; nothing links them explicitly.
create table deals (
    id bigint generated by default as identity primary key,
    streamer varchar(255) not null,
    sponsor varchar(255) not null,
    starts_at bigint not null,
    ends_at bigint,
    promised_streams integer,
    fee double precision,
    currency varchar(8) not null default 'USD',
    cpm_per_30s_equivalent double precision not null,
    host_read_rate_per_1000 double precision not null,
    tracked_link varchar(1024),
    chat_command varchar(64),
    channel_point_reward varchar(255),
    created_at bigint not null,
    updated_at bigint not null
);

create index idx_deals_streamer_starts
    on deals (streamer, starts_at desc);
